2019-03-24 20:42:27 [scrapy.utils.log] INFO: Scrapy 1.3.3 started (bot: JDSpider)
2019-03-24 20:42:27 [scrapy.utils.log] INFO: Overridden settings: {'BOT_NAME': 'JDSpider', 'HTTPCACHE_ENABLED': True, 'LOG_FILE': 'logs\\JDSpider\\getCommentDetail\\456418f84e3211e9bd3face010528bab.log', 'NEWSPIDER_MODULE': 'JDSpider.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['JDSpider.spiders'], 'USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'}
2019-03-24 20:42:27 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2019-03-24 20:42:27 [scrapy.middleware] WARNING: Disabled HttpCacheMiddleware: Unable to find scrapy.cfg file to infer project data dir
2019-03-24 20:42:27 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-03-24 20:42:27 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-03-24 20:42:27 [py.warnings] WARNING: c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py:11: ScrapyDeprecationWarning: Module `scrapy.log` has been deprecated, Scrapy now relies on the builtin Python library for logging. Read the updated logging entry in the documentation to learn more.

2019-03-24 20:42:27 [scrapy.middleware] INFO: Enabled item pipelines:
['JDSpider.pipelines.JdspiderPipeline']
2019-03-24 20:42:27 [scrapy.core.engine] INFO: Spider opened
2019-03-24 20:42:27 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-03-24 20:42:27 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2019-03-24 20:42:27 [scrapy.core.engine] DEBUG: Crawled (404) <GET http://sclub.jd.com/robots.txt> (referer: None)
2019-03-24 20:42:27 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1> (referer: None)
2019-03-24 20:42:28 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=29> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=22> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=26> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=23> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=24> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=27> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=29> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=28> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=21> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=22> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=26> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=16> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=20> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=18> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=17> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=23>
{'commodityId': '8141909',
 'content': '是正品，呼吸灯很漂亮，按键反馈也很棒，不错的游戏鼠标，值得推荐！',
 'creationTime': '2019-02-16 08:47:36',
 'isTop': False,
 'picNum': 2,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '铜牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=23>
{'commodityId': '8141909',
 'content': '电脑超级帅，家在小县城，没想到第二天就到了，激动坏了，特别喜欢',
 'creationTime': '2019-02-14 22:52:50',
 'isTop': False,
 'picNum': 2,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': 'PLUS会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=23>
{'commodityId': '8141909',
 'content': '很舒服，用着手感不错，一直想买个雷蛇鼠标，终于攒够钱了，就买了，很喜欢，终于可以开心的吃鸡了，玩联盟一定会有五杀的机会????',
 'creationTime': '2018-05-19 12:52:55',
 'isTop': False,
 'picNum': 8,
 'replyNum': 1,
 'score': 5,
 'usefulVoteCount': 1,
 'userLevelName': '银牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=23> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=24> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=19> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=27> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=12> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=15> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=14> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=28> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=21> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=16> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=11> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=13> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=20> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=18> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=17>
{'commodityId': '8141909',
 'content': '灵敏度高。老公自己选的。觉得很喜欢。满意的不行。以后有需要再来',
 'creationTime': '2019-01-10 09:11:51',
 'isTop': False,
 'picNum': 2,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '金牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=17> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=10> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=19> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=9> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=25> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=8> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=7> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=12> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=15>
{'commodityId': '8141909',
 'content': '非常不错的鼠标，手感特别好，很好用。指针速度特别合适，相比之前的鼠标更稳定。',
 'creationTime': '2018-12-13 19:53:15',
 'isTop': False,
 'picNum': 1,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': 'PLUS会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=15> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=14> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=11> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=13> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=5> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=6> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=10>
{'commodityId': '8141909',
 'content': '这个鼠标手感很舒服，鼠标大小也很合适但是不太适合手小的人，抓不住。价格也很实惠配合鼠标驱动可以自己调五档dpi适合玩FPS游戏，英雄联盟也没问题。',
 'creationTime': '2019-01-25 16:25:14',
 'isTop': False,
 'picNum': 0,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': 'PLUS会员[试用]',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=10>
{'commodityId': '8141909',
 'content': '东西很好，价美物廉，谢谢掌柜的！说实在，这是我网上购物来让我最满意的一次购物。无论是掌柜的态度还是对物品，我都非常满意的。掌柜态度很专业热情，有问必答，回复也很快，我问了不少问题，他都不觉得烦，都会认真回答我，这点我向掌柜表示由衷的敬意，这样的好掌柜可不多。再说宝贝，正是我需要的，收到的时候包装完整，打开后让我惊喜的是，宝贝比我想象中的还要好！不得不得竖起大拇指。说了这么久，嗯没错，就是凑字数呢',
 'creationTime': '2019-02-22 20:19:21',
 'isTop': False,
 'picNum': 0,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': 'PLUS会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=10> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=3> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=4> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=2> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=9> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=25> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=8> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=7> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=5> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=6> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=3> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=4>
{'commodityId': '8141909',
 'content': '真是太棒了！！！！用蝰蛇十年了，鼠标寿命基本上在五年以上，除非自己不用。近期买的蝰蛇用了将近一年，滚轮出现回滚问题，商家二话不说直接换新，果然是大牌产品，售后服务好，大气！京东快递也很棒，都认识我了，直接给送到办公室，很好???',
 'creationTime': '2019-02-14 17:08:01',
 'isTop': False,
 'picNum': 1,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '金牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=4> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=2> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0>
{'commodityId': '8141909',
 'content': '昏暗灯光下非常炫酷，鼠标比较适合大手，本人手大，小手的别选。键盘鼠标都是雷蛇，整体感觉非常棒，关机后灯光自动全部熄灭。管控端有点太专业，需要学习下才能适应。灯光效果可调，也可以自定义效果，按键功能也可以自定义。',
 'creationTime': '2018-04-12 15:45:06',
 'isTop': False,
 'picNum': 3,
 'replyNum': 1,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '钻石会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0>
{'commodityId': '8141909',
 'content': '够大 握在手里很有感觉 有分量 不是那轻飘飘的 我是做品牌设计的 经常需要用鼠标画图 这样的鼠标不可多得 颜色很正 清新脱俗 '
            '不是那一片黑 logo上有呼吸灯 很漂亮 两个快捷键很好用 我设置为**某特定软件和切换桌面 很爽啊 提高效率非他莫属',
 'creationTime': '2018-09-28 16:42:13',
 'isTop': False,
 'picNum': 0,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': 'PLUS会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0>
{'commodityId': '8141909',
 'content': '第一次卖雷蛇的，我手比较大，这个很合适，手感很好(?▽?)！但是如果你有手汗的话会很明显沾在上面，材质问题吧！其他的还好。有配置的软件，有些东西可以自己调，很好用。鼠标线是编织线，也很好。',
 'creationTime': '2019-03-15 22:09:26',
 'isTop': False,
 'picNum': 0,
 'replyNum': 2,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '铜牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] DEBUG: Scraped from <200 http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0>
{'commodityId': '8141909',
 'content': '作为女生，这个白色的鼠标简直超级满足啊，好漂亮啊，干干净净的。鼠标比较大，手小的女生慎重，我属于手比较大长的那种，这个刚刚好。但是真的好漂亮啊！鼠标绳还是布的，真的超级可爱',
 'creationTime': '2019-03-02 18:47:13',
 'isTop': False,
 'picNum': 3,
 'replyNum': 0,
 'score': 5,
 'usefulVoteCount': 0,
 'userLevelName': '银牌会员',
 'videoNum': 1}
2019-03-24 20:42:28 [scrapy.core.scraper] ERROR: Spider error processing <GET http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=0> (referer: http://sclub.jd.com/comment/productPageComments.action?callback=fetchJSON_comment98vv74&productId=8141909&score=0&sortType=5&pageSize=10&isShadowSku=0&fold=1&page=1)
Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "d:\anacaonda\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\spiders\getCommentDetail.py", line 42, in getCommentDetail
    item['videoNum'] = len(comment['videos'])
KeyError: 'videos'
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [scrapy.core.engine] INFO: Closing spider (finished)
2019-03-24 20:42:28 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 18768,
 'downloader/request_count': 31,
 'downloader/request_method_count/GET': 31,
 'downloader/response_bytes': 207388,
 'downloader/response_count': 31,
 'downloader/response_status_count/200': 30,
 'downloader/response_status_count/404': 1,
 'dupefilter/filtered': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 3, 24, 12, 42, 28, 762609),
 'item_scraped_count': 12,
 'log_count/CRITICAL': 18,
 'log_count/DEBUG': 45,
 'log_count/ERROR': 29,
 'log_count/INFO': 7,
 'log_count/WARNING': 2,
 'request_depth_max': 1,
 'response_received_count': 31,
 'scheduler/dequeued': 30,
 'scheduler/dequeued/memory': 30,
 'scheduler/enqueued': 30,
 'scheduler/enqueued/memory': 30,
 'spider_exceptions/KeyError': 29,
 'start_time': datetime.datetime(2019, 3, 24, 12, 42, 27, 597265)}
2019-03-24 20:42:28 [scrapy.core.engine] INFO: Spider closed (finished)
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
2019-03-24 20:42:28 [twisted] CRITICAL: Unhandled error in Deferred:
2019-03-24 20:42:28 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 78, in _insert_record_comment
    txn.execute(sql_insert)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "d:\anacaonda\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "d:\anacaonda\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "d:\anacaonda\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1136, "Column count doesn't match value count at row 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "d:\anacaonda\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "d:\anacaonda\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 475, in _runInteraction
    compat.reraise(excValue, excTraceback)
  File "d:\anacaonda\lib\site-packages\twisted\python\compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "d:\anacaonda\lib\site-packages\twisted\enterprise\adbapi.py", line 465, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "c:\users\柘宇\appdata\local\temp_~1\jdspider-1553431321-breiuds5.egg\JDSpider\pipelines.py", line 80, in _insert_record_comment
    raise Exception("When inserting comment into DB, error occurred.")
Exception: When inserting comment into DB, error occurred.
